# MPLAB IDE generated this makefile for use with GNU make.
# Project: base-lcd.mcp
# Date: Wed Jan 19 23:28:45 2011

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = del

base-lcd.cof : base-lcd.o busyxlcd.o openxlcd.o putrxlcd.o putsxlcd.o readaddr.o readdata.o setcgram.o setddram.o wcmdxlcd.o writdata.o
	$(LD) /p18F2550 /l"C:\Program Files\Microchip\mplabc18\v3.37.01\lib" "base-lcd.o" "busyxlcd.o" "openxlcd.o" "putrxlcd.o" "putsxlcd.o" "readaddr.o" "readdata.o" "setcgram.o" "setddram.o" "wcmdxlcd.o" "writdata.o" /u_CRUNTIME /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"base-lcd.cof" /M"base-lcd.map" /W

base-lcd.o : base-lcd.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/xlcd.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/delays.h base-lcd.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18f2550.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18cxxx.h
	$(CC) -p=18F2550 "base-lcd.c" -fo="base-lcd.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

busyxlcd.o : xlcd/busyxlcd.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/xlcd.h xlcd/busyxlcd.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18cxxx.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18f2550.h
	$(CC) -p=18F2550 "xlcd\busyxlcd.c" -fo="busyxlcd.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

openxlcd.o : xlcd/openxlcd.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/delays.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/xlcd.h xlcd/openxlcd.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18cxxx.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18f2550.h
	$(CC) -p=18F2550 "xlcd\openxlcd.c" -fo="openxlcd.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

putrxlcd.o : xlcd/putrxlcd.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/xlcd.h xlcd/putrxlcd.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18cxxx.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18f2550.h
	$(CC) -p=18F2550 "xlcd\putrxlcd.c" -fo="putrxlcd.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

putsxlcd.o : xlcd/putsxlcd.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/xlcd.h xlcd/putsxlcd.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18cxxx.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18f2550.h
	$(CC) -p=18F2550 "xlcd\putsxlcd.c" -fo="putsxlcd.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

readaddr.o : xlcd/readaddr.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/xlcd.h xlcd/readaddr.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18cxxx.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18f2550.h
	$(CC) -p=18F2550 "xlcd\readaddr.c" -fo="readaddr.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

readdata.o : xlcd/readdata.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/xlcd.h xlcd/readdata.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18cxxx.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18f2550.h
	$(CC) -p=18F2550 "xlcd\readdata.c" -fo="readdata.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

setcgram.o : xlcd/setcgram.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/xlcd.h xlcd/setcgram.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18cxxx.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18f2550.h
	$(CC) -p=18F2550 "xlcd\setcgram.c" -fo="setcgram.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

setddram.o : xlcd/setddram.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/xlcd.h xlcd/setddram.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18cxxx.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18f2550.h
	$(CC) -p=18F2550 "xlcd\setddram.c" -fo="setddram.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

wcmdxlcd.o : xlcd/wcmdxlcd.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/xlcd.h xlcd/wcmdxlcd.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18cxxx.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18f2550.h
	$(CC) -p=18F2550 "xlcd\wcmdxlcd.c" -fo="wcmdxlcd.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

writdata.o : xlcd/writdata.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/xlcd.h xlcd/writdata.c ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18cxxx.h ../../../../../../../Program\ Files/Microchip/mplabc18/v3.37.01/h/p18f2550.h
	$(CC) -p=18F2550 "xlcd\writdata.c" -fo="writdata.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

clean : 
	$(RM) "base-lcd.o" "busyxlcd.o" "openxlcd.o" "putrxlcd.o" "putsxlcd.o" "readaddr.o" "readdata.o" "setcgram.o" "setddram.o" "wcmdxlcd.o" "writdata.o" "base-lcd.cof" "base-lcd.hex"

